version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - npm install --silent --no-progress
  build:
    commands:
      - npm run-script lint
      - npm run test
      - mkdir -p target/stg
      - mkdir -p target/prod
      - serverless package --package target/stg --stage $env -v -r ap-south-1
      - serverless package --package target/prod --stage $env -v -r ap-south-1

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
