service: gimme-time

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    STAGE: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::codepipeline-ap-south-1-450231656010/gimme-time-pipeline/BuildArtif/*"

functions:
  gimmetime:
    handler: handler.handler
    events:
      - http:
          path: /time
          method: get
          request:
            parameters:
              querystrings:
                tz: true

plugins:
  - serverless-scriptable-plugin
