service: gimme-time

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    STAGE: ${opt:stage}

functions:
  gimmetime:
    handler: handler.gimmetime
    events:
      - http:
          path: /time
          method: get
          request:
            parameters:
              querystrings:
                tz: true

custom:
  package:
    command: npm run package
    include:
      - .serverless/**
    excludeDevDependencies: true

plugins:
  - serverless-scriptable-plugin
